"""Explicit signal and preemption state enumerations."""

from enum import Enum
from .protocol import SignalColour


class NormalPhase(str, Enum):
    ALL_RED_BEFORE_NORTH = "ALL_RED_BEFORE_NORTH"
    NORTH_GREEN = "NORTH_GREEN"
    NORTH_YELLOW = "NORTH_YELLOW"
    ALL_RED_BEFORE_EAST = "ALL_RED_BEFORE_EAST"
    EAST_GREEN = "EAST_GREEN"
    EAST_YELLOW = "EAST_YELLOW"
    ALL_RED_BEFORE_SOUTH = "ALL_RED_BEFORE_SOUTH"
    SOUTH_GREEN = "SOUTH_GREEN"
    SOUTH_YELLOW = "SOUTH_YELLOW"
    ALL_RED_BEFORE_WEST = "ALL_RED_BEFORE_WEST"
    WEST_GREEN = "WEST_GREEN"
    WEST_YELLOW = "WEST_YELLOW"
    ALL_RED_BEFORE_NS = "ALL_RED_BEFORE_NS"
    NS_GREEN = "NS_GREEN"
    NS_YELLOW = "NS_YELLOW"
    ALL_RED_BEFORE_EW = "ALL_RED_BEFORE_EW"
    EW_GREEN = "EW_GREEN"
    EW_YELLOW = "EW_YELLOW"


class PreemptionState(str, Enum):
    NORMAL = "NORMAL"
    REQUEST_VALIDATION = "REQUEST_VALIDATION"
    PREEMPTION_PENDING = "PREEMPTION_PENDING"
    CLEAR_CURRENT_GREEN = "CLEAR_CURRENT_GREEN"
    ALL_RED_CLEARANCE = "ALL_RED_CLEARANCE"
    AMBULANCE_GREEN = "AMBULANCE_GREEN"
    PASSAGE_MONITORING = "PASSAGE_MONITORING"
    RECOVERY_YELLOW = "RECOVERY_YELLOW"
    RECOVERY_ALL_RED = "RECOVERY_ALL_RED"
    RETURN_TO_NORMAL = "RETURN_TO_NORMAL"
    FAIL_SAFE = "FAIL_SAFE"
