"""Explicit signal and preemption state enumerations."""

from enum import Enum


class SignalColour(str, Enum):
    RED = "RED"
    YELLOW = "YELLOW"
    GREEN = "GREEN"


class NormalPhase(str, Enum):
    ALL_RED_BEFORE_NS = "ALL_RED_BEFORE_NS"
    NS_GREEN = "NS_GREEN"
    NS_YELLOW = "NS_YELLOW"
    ALL_RED_BEFORE_EW = "ALL_RED_BEFORE_EW"
    EW_GREEN = "EW_GREEN"
    EW_YELLOW = "EW_YELLOW"


class PreemptionState(str, Enum):
    NORMAL = "NORMAL"
    REQUEST_VALIDATION = "REQUEST_VALIDATION"
    PREEMPTION_PENDING = "PREEMPTION_PENDING"
    CLEAR_CURRENT_GREEN = "CLEAR_CURRENT_GREEN"
    ALL_RED_CLEARANCE = "ALL_RED_CLEARANCE"
    AMBULANCE_GREEN = "AMBULANCE_GREEN"
    PASSAGE_MONITORING = "PASSAGE_MONITORING"
    RECOVERY_YELLOW = "RECOVERY_YELLOW"
    RECOVERY_ALL_RED = "RECOVERY_ALL_RED"
    RETURN_TO_NORMAL = "RETURN_TO_NORMAL"
    FAIL_SAFE = "FAIL_SAFE"
