"""Generate checked-in Python/Kotlin wire enums and Android registry from shared sources."""
from pathlib import Path
import json
import yaml

ROOT = Path(__file__).resolve().parents[1]


def generate():
    shared = ROOT / "shared"
    contract = json.loads((shared / "protocol.json").read_text(encoding="utf-8"))
    python = '"""Generated by scripts/generate_shared_contract.py; edit shared/protocol.json."""\nfrom enum import Enum\n\n'
    kotlin = '// Generated by scripts/generate_shared_contract.py; edit shared/protocol.json.\npackage org.lifelane.mobile\n\n'
    for name, values in contract["enums"].items():
        python += f'class {name}(str, Enum):\n' + ''.join(f'    {v} = "{v}"\n' for v in values) + '\n'
        kotlin += f'enum class {name} {{ '+', '.join(values)+' }\n'
    (ROOT/"raspberry_pi_app/core/protocol.py").write_text(python,encoding="utf-8")
    (ROOT/"android_app/app/src/main/java/org/lifelane/mobile/Protocol.kt").write_text(kotlin,encoding="utf-8")
    config = yaml.safe_load((ROOT/"config/junction.yaml").read_text(encoding="utf-8"))
    (shared/"junction.json").write_text(json.dumps(config,indent=2)+"\n",encoding="utf-8")
    catalog=[config]+[yaml.safe_load(path.read_text(encoding="utf-8")) for path in sorted((ROOT/"config/junctions").glob("*.yaml"))]
    ids=[item["junction"]["id"] for item in catalog]
    controllers=[item["junction"]["controller_id"] for item in catalog]
    if len(set(ids))!=len(ids) or len(set(controllers))!=len(controllers):
        raise ValueError("Junction and controller IDs must be unique across the catalog")
    (shared/"junctions.json").write_text(json.dumps({"schemaVersion":2,"junctions":catalog},indent=2)+"\n",encoding="utf-8")


if __name__ == "__main__":
    generate()
